### ISSUE TITLE
Links nas grades de palestras

### ISSUE THREAD

**Issue by raffaeldutra** [fossday/website-hugo#8]
Problema: quando clico em cima de um horário da palestra, sou "jogado" para a home.
Solução: ou removemos os links dos horários, ou ele deverá trazer algum tipo de informação referente a este horário.

**Comment by tomkiel** [comment]
Removidos os links na grade de palestras. 
Aguardando mais testes...

**Comment by raffaeldutra** [comment]
@rtomkiel aparentemente resolvido, certo? vou fechar a issue.
